name: gaussian_mip
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - opacus=1.4.0
  - pip=23.0.1
  - python=3.10.10
  - readline=8.2
  - setuptools=66.0.0
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - ipywidgets==8.1.2
      - huggingface-hub==0.14.1
      - ipykernel==6.22.0
      - ipython==8.12.0
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - matplotlib==3.7.1
      - numpy==1.24.2
      - pandas==2.0.1
      - pillow==9.5.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - shap==0.45.0
      - torch==2.0.0
      - torchvision==0.15.1      
      - transformers==4.40.2
      - tqdm==4.65.0
