name: gaussian_mip
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - opacus=1.4.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - pip=23.0.1
  - python=3.10.10
  - python_abi=3.10
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - cmake==3.26.3
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - executing==1.2.0
      - filelock==3.12.0
      - fonttools==4.39.3
      - fsspec==2023.4.0
      - functorch==2.0.0
      - huggingface-hub==0.14.1
      - idna==3.4
      - ipykernel==6.22.0
      - ipython==8.12.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - kiwisolver==1.4.4
      - lit==16.0.1
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - numpy==1.24.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pandas==2.0.1
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.2.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.0.2
      - requests==2.28.2
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - six==1.16.0
      - sklearn==0.0.post4
      - stack-data==0.6.2
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - timm==0.6.13
      - torch==2.0.0
      - torchvision==0.15.1
      - tornado==6.3
      - tqdm==4.65.0
      - traitlets==5.9.0
      - triton==2.0.0
      - tzdata==2023.3
      - urllib3==1.26.15
      - wcwidth==0.2.6
